import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;
  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations)!;
  }

  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      'app_title': 'Virtual Lawyer',
      'new_chat': 'New Chat',
      'find_lawyer': 'Find a Lawyer',
      'settings': 'Settings',
      'booking_requests': 'Booking Requests',
      'my_schedule': 'My Schedule',
      'profile': 'Profile',
      'logout': 'Logout',
      'language': 'Language',
      'about': 'About',
      'save': 'SAVE',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'case_brief': 'Case Brief',
      'consultation_fee': 'Consultation Fee',
      'confirm_consultation': 'Confirm Consultation',
      'review_request': 'Review your request for Egyptian Statute consultation.',
      'selected_date_time': 'SELECTED DATE & TIME',
      'counselor': 'COUNSELOR',
      'tell_lawyer_about_case': 'TELL THE LAWYER ABOUT YOUR CASE BRIEF',
      'required_field': 'Required Field',
      'confirm_send_request': 'Confirm & Send Request',
      'recent_history': 'RECENT HISTORY',
      'version': 'VERSION',
      'refine_legal_agency': 'Refine Your Legal Agency.',
      'welcome_back': 'Welcome Back',
      'legal_expertise': 'Legal Expertise at your fingertips.',
      'continue_as_guest': 'CONTINUE AS GUEST',
      'search_lawyer': 'Search for a Lawyer...',
      'top_rated': 'TOP RATED LAWYERS',
      'send_message': 'Send message...',
      'chat_hint': 'Ask anything about legal matters...',
      'login': 'Login',
      'signup': 'Sign Up',
      'excellence_in_jurisprudence': 'EXCELLENCE IN JURISPRUDENCE',
      'log_in_to_account': 'Log in to your Virtual Lawyer account',
      'forgot_password': 'Forgot Password?',
      'dont_have_account': "Don't have an account?",
      'create_account': 'Create Account',
      'join_to_get_started': 'Join Virtual Lawyer to get started',
      'user': 'User',
      'lawyer': 'Lawyer',
      'full_name': 'Full Name',
      'email_address': 'Email Address',
      'password': 'Password',
      'primary_city': 'Primary City',
      'birth_date': 'Birth Date',
      'phone_number': 'Phone Number',
      'whatsapp_line': 'WhatsApp Line',
      'specialization': 'Specialization',
      'select_specialization': 'Select Specialization',
      'office_address': 'Office Address',
      'consultation_fee_egp': 'Consultation Fee (EGP)',
      'professional_bio': 'Professional Bio',
      'already_have_account': 'Already have an account?',
      'edit_profile': 'Edit Profile',
      'save_changes': 'Save Changes',
      'profile_updated': 'Profile Updated Successfully!',
      'your_name': 'Your Name',
      'find_your_counsel': 'Find your Counsel.',
      'search_by_name_city': 'Search by Name or City',
      'no_lawyers_found': 'No lawyers found matching criteria.',
      'consultation': 'CONSULTATION',
      'view_profile': 'View Profile',
      'reviews': 'reviews',
      'manage_incoming_mandates': 'Manage your incoming mandates and scheduled consultations. Every decision here carries the weight of the Egyptian Statutes.',
      'confirmed': 'CONFIRMED',
      'pending': 'PENDING',
      'pending_review': 'PENDING REVIEW',
      'completed': 'COMPLETED',
      'commercial_arbitration': 'COMMERCIAL ARBITRATION',
      'case_brief_label': 'Case Brief:',
      'accept_mandate': 'Accept Mandate',
      'reject': 'Reject',
      'view_file': 'View File',
      'archive': 'Archive',
      'my_availability': 'My Availability',
      'set_weekly_slots': 'SET WEEKLY SLOTS',
      'manage_default_hours': 'Manage your default working hours',
      'time_slots': 'TIME SLOTS',
      'select_available_times': 'Select available times for the chosen date',
      'add_custom_time_slot': 'Add Custom Time Slot',
      'mark_day_closed': 'Mark Day as Closed',
      'view_personal_details': 'View Personal Details',
      'toggle_language': 'Toggle display language',
      'manage_appointments': 'Manage appointments',
      'manage_availability': 'Manage your availability',
      'about_project': 'About Virtual Lawyer Project',
      'archived': 'Archived',
      'property_dispute_analysis': 'Property Dispute Analysis',
      'hours_ago': 'hours ago',
      'consultation_schedule': 'Consultation Schedule',
      'cairo_time': 'CAIRO TIME (GMT+3)',
      'office': 'OFFICE',
      'fee': 'FEE',
      'law_office_location': 'Law Office Location',
      'confirm_booking_for': 'Confirm Booking for',
      'provide_case_brief': 'Please provide a case brief before confirming.',
      'booking_request_sent': 'Booking Request Sent to Adv.',
      'case_brief_hint': 'Provide a concise summary of your legal inquiry regarding Egyptian Statutes or Administrative law...',
      'sovereign_tier_specialist': 'Sovereign Tier Specialist',
      'senior_litigation_partner': 'Senior Litigation Partner',
      'whatsapp': 'WHATSAPP',
      'phone': 'PHONE',
      'guest_feature_message': 'To use this feature, sign in / log in.',
      'sign_in_prompt': 'Sign in to unlock all features',
      'go_to_login': 'Sign In',
      'back_to_home': 'Back to Home',
      'new_conversation': 'New Conversation',
      // Specializations
      'spec_all': 'All',
      'spec_criminal_law': 'Criminal Law',
      'spec_family_law': 'Family Law',
      'spec_corporate_law': 'Corporate Law',
      'spec_real_estate_law': 'Real Estate Law',
      'spec_civil_rights': 'Civil Rights',
      'spec_immigration_law': 'Immigration Law',
      'spec_intellectual_property': 'Intellectual Property',
      'spec_other': 'Other',
      'cancel_request': 'Cancel Request',
      'request_details': 'Request Details',
      'my_bookings': 'My Bookings',
      'manage_your_bookings': 'Manage the status of your legal consultation requests.',
      'bio_ahmed': 'Senior Criminal Litigator with 15 years of experience in high-profile cases.',
      'bio_layla': 'Corporate & Commercial Law expert, handling mergers and acquisitions.',
      'bio_mahmoud': 'Family & Civil Specialist dedicated to peaceful dispute resolutions.',
      'bio_default': 'Specializing in Egyptian constitutional law and international arbitration. With over 20 years of experience in the Courts of Cairo, providing elite legal counsel for complex statutory disputes and high-stakes corporate litigation.',
    },
    'ar': {
      'app_title': 'المحامي الافتراضي',
      'new_chat': 'دردشة جديدة',
      'find_lawyer': 'ابحث عن محامي',
      'settings': 'الإعدادات',
      'booking_requests': 'طلبات الحجز',
      'my_schedule': 'جدولي',
      'profile': 'الملف الشخصي',
      'logout': 'تسجيل الخروج',
      'language': 'اللغة',
      'about': 'حول التطبيق',
      'save': 'حفظ',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'case_brief': 'ملخص القضية',
      'consultation_fee': 'رسوم الاستشارة',
      'confirm_consultation': 'تأكيد الاستشارة',
      'review_request': 'راجع طلبك لاستشارة القوانين المصرية.',
      'selected_date_time': 'التاريخ والوقت المختار',
      'counselor': 'المستشار',
      'tell_lawyer_about_case': 'أخبر المحامي عن ملخص قضيتك',
      'required_field': 'حقل مطلوب',
      'confirm_send_request': 'تأكيد وإرسال الطلب',
      'recent_history': 'السجل الأخير',
      'version': 'الإصدار',
      'refine_legal_agency': 'طور وكالتك القانونية.',
      'welcome_back': 'مرحباً بك مجدداً',
      'legal_expertise': 'الخبرة القانونية بين يديك.',
      'continue_as_guest': 'الدخول كزائر',
      'search_lawyer': 'ابحث عن محامي...',
      'top_rated': 'كبار المحامين',
      'send_message': 'أرسل رسالة...',
      'chat_hint': 'اسأل عن أي أمور قانونية...',
      'login': 'تسجيل الدخول',
      'signup': 'إنشاء حساب',
      'excellence_in_jurisprudence': 'التميز في الفقه القانوني',
      'log_in_to_account': 'سجل دخولك إلى حسابك في المحامي الافتراضي',
      'forgot_password': 'نسيت كلمة المرور؟',
      'dont_have_account': 'ليس لديك حساب؟',
      'create_account': 'إنشاء حساب',
      'join_to_get_started': 'انضم إلى المحامي الافتراضي للبدء',
      'user': 'مستخدم',
      'lawyer': 'محامي',
      'full_name': 'الاسم الكامل',
      'email_address': 'البريد الإلكتروني',
      'password': 'كلمة المرور',
      'primary_city': 'المدينة الرئيسية',
      'birth_date': 'تاريخ الميلاد',
      'phone_number': 'رقم الهاتف',
      'whatsapp_line': 'واتساب',
      'specialization': 'التخصص',
      'select_specialization': 'اختر التخصص',
      'office_address': 'عنوان المكتب',
      'consultation_fee_egp': 'رسوم الاستشارة (جنيه مصري)',
      'professional_bio': 'نبذة مهنية',
      'already_have_account': 'لديك حساب بالفعل؟',
      'edit_profile': 'تعديل الملف الشخصي',
      'save_changes': 'حفظ التغييرات',
      'profile_updated': 'تم تحديث الملف الشخصي بنجاح!',
      'your_name': 'اسمك',
      'find_your_counsel': 'ابحث عن مستشارك.',
      'search_by_name_city': 'البحث بالاسم أو المدينة',
      'no_lawyers_found': 'لم يتم العثور على محامين مطابقين للمعايير.',
      'consultation': 'الاستشارة',
      'view_profile': 'عرض الملف',
      'reviews': 'تقييمات',
      'manage_incoming_mandates': 'قم بإدارة التوكيلات الواردة والاستشارات المجدولة. كل قرار هنا يحمل ثقل القوانين المصرية.',
      'confirmed': 'مؤكد',
      'pending': 'قيد الانتظار',
      'pending_review': 'قيد المراجعة',
      'completed': 'مكتمل',
      'commercial_arbitration': 'التحكيم التجاري',
      'case_brief_label': 'ملخص القضية:',
      'accept_mandate': 'قبول التوكيل',
      'reject': 'رفض',
      'view_file': 'عرض الملف',
      'archive': 'أرشفة',
      'my_availability': 'أوقات توفري',
      'set_weekly_slots': 'تحديد المواعيد الأسبوعية',
      'manage_default_hours': 'إدارة ساعات العمل الافتراضية',
      'time_slots': 'المواعيد الزمنية',
      'select_available_times': 'اختر الأوقات المتاحة لليوم المحدد',
      'add_custom_time_slot': 'إضافة موعد مخصص',
      'mark_day_closed': 'تحديد اليوم كمغلق',
      'view_personal_details': 'عرض البيانات الشخصية',
      'toggle_language': 'تغيير لغة العرض',
      'manage_appointments': 'إدارة المواعيد',
      'manage_availability': 'إدارة أوقات توفرك',
      'about_project': 'حول مشروع المحامي الافتراضي',
      'archived': 'مؤرشف',
      'property_dispute_analysis': 'تحليل نزاع عقاري',
      'hours_ago': 'ساعات مضت',
      'consultation_schedule': 'جدول الاستشارات',
      'cairo_time': 'توقيت القاهرة (GMT+3)',
      'office': 'المكتب',
      'fee': 'الرسوم',
      'law_office_location': 'موقع مكتب المحاماة',
      'confirm_booking_for': 'تأكيد الحجز ليوم',
      'provide_case_brief': 'يرجى تقديم ملخص القضية قبل التأكيد.',
      'booking_request_sent': 'تم إرسال طلب الحجز إلى المحامي',
      'case_brief_hint': 'قدم ملخصاً موجزاً لاستفسارك القانوني المتعلق بالقوانين المصرية أو القانون الإداري...',
      'sovereign_tier_specialist': 'أخصائي المستوى السيادي',
      'senior_litigation_partner': 'شريك أقدم في التقاضي',
      'whatsapp': 'واتساب',
      'phone': 'الهاتف',
      'guest_feature_message': 'لاستخدام هذه الميزة، يرجى تسجيل الدخول.',
      'sign_in_prompt': 'سجل دخولك لفتح جميع الميزات',
      'go_to_login': 'تسجيل الدخول',
      'back_to_home': 'العودة للرئيسية',
      'new_conversation': 'محادثة جديدة',
      // Specializations
      'spec_all': 'الكل',
      'spec_criminal_law': 'القانون الجنائي',
      'spec_family_law': 'قانون الأسرة',
      'spec_corporate_law': 'قانون الشركات',
      'spec_real_estate_law': 'القانون العقاري',
      'spec_civil_rights': 'الحقوق المدنية',
      'spec_immigration_law': 'قانون الهجرة',
      'spec_intellectual_property': 'الملكية الفكرية',
      'spec_other': 'أخرى',
      'cancel_request': 'إلغاء الطلب',
      'request_details': 'تفاصيل الطلب',
      'my_bookings': 'حجوزاتي',
      'manage_your_bookings': 'إدارة حالة طلبات الاستشارة القانونية الخاصة بك.',
      'bio_ahmed': 'محامي جنائي أقدم يتمتع بخبرة 15 عاماً في القضايا رفيعة المستوى.',
      'bio_layla': 'خبيرة في القانون التجاري وقانون الشركات، متخصصة في عمليات الدمج والاستحواذ.',
      'bio_mahmoud': 'متخصص في قانون الأسرة والقانون المدني ملتزم بحل النزاعات بطرق سلمية.',
      'bio_default': 'متخصص في القانون الدستوري المصري والتحكيم الدولي. يتمتع بخبرة تزيد عن 20 عاماً في محاكم القاهرة، ويقدم استشارات قانونية متميزة في النزاعات القانونية المعقدة والتقاضي التجاري.',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ?? key;
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
